# Generated by Django 3.0.5 on 2020-04-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', '-year', '-doors']},
        ),
    ]
